spring.application.name=shape-designer

spring.datasource.url=jdbc:mysql://localhost:3306/shape_designer
spring.datasource.username=root
spring.datasource.password=MY_PASSWORD

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

server.port=8080
